spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: 'root##root'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  servlet:
    context-path: /tarea
  port: 8080